version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: ./build/api/Dockerfile
    image: go-web-api
    environment:
      - DB_URI=mongodb://mongodb:27017
      - DB_NAME=DB
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb

  consumer:
    build:
      context: ./
      dockerfile: ./build/kafka/Dockerfile
    image: go-web-kafka
    environment:
      - DB_URI=mongodb://mongodb:27017
      - DB_NAME=DB
      - BOOTSTRAP_SERVER=kafka:9092
    links:
      - mongodb
    depends_on:
      - kafka
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092"]
      timeout: 45s
      interval: 10s
      retries: 10
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
